# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json from the parent directory into the working directory
COPY ../package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code into the working directory
COPY . .

# Build the React application
RUN npm run build

# Use a smaller image for serving the build files
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
