apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: scd-final-lab-exam-durrami-database:latest
        ports:
        - containerPort: 6000  # Port your database application is listening on
        env:
        - name: NODE_ENV
          value: production
